/*
 * Vencord, a Discord client mod
 * Copyright (c) 2024 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * Vencord, a Discord client mod
 * Copyright (c) 2024 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
export const CoolTextMap = [
    { "fontId": "758277984", "displayname": "Saint Patrick", "url": "https://ct.mob0.com/Logo/Saint-Patrick.png" },
    { "fontId": "4", "displayname": "Burning", "url": "https://ct.mob0.com/Logo/Burning.gif" },
    { "fontId": "758279718", "displayname": "Keen", "url": "https://ct.mob0.com/Logo/Keen.png" },
    { "fontId": "780833150", "displayname": "Skate", "url": "https://ct.mob0.com/Logo/Skate.png" },
    { "fontId": "1009848424", "displayname": "Fun", "url": "https://ct.mob0.com/Logo/Fun.png" },
    { "fontId": "732438332", "displayname": "White", "url": "https://ct.mob0.com/Logo/White.png" },
    { "fontId": "2975689126", "displayname": "Tribal", "url": "https://ct.mob0.com/Logo/Tribal.png" },
    { "fontId": "2650967346", "displayname": "Supernova", "url": "https://ct.mob0.com/Logo/Supernova.png" },
    { "fontId": "13", "displayname": "Fire", "url": "https://ct.mob0.com/Logo/Fire.png" },
    { "fontId": "37", "displayname": "iText", "url": "https://ct.mob0.com/Logo/iText.png" },
    { "fontId": "791030843", "displayname": "Easy", "url": "https://ct.mob0.com/Logo/Easy.png" },
    { "fontId": "26", "displayname": "Animated Glow", "url": "https://ct.mob0.com/Logo/Animated-Glow.gif" },
    { "fontId": "732443655", "displayname": "Gold Trim", "url": "https://ct.mob0.com/Logo/Gold-Trim.png" },
    { "fontId": "732429307", "displayname": "Legal", "url": "https://ct.mob0.com/Logo/Legal.png" },
    { "fontId": "21", "displayname": "Simple", "url": "https://ct.mob0.com/Logo/Simple.png" },
    { "fontId": "1779834160", "displayname": "Ice Cube", "url": "https://ct.mob0.com/Logo/Ice-Cube.png" },
    { "fontId": "4113131447", "displayname": "Tesla", "url": "https://ct.mob0.com/Logo/Tesla.png" },
    { "fontId": "7", "displayname": "Chrome One", "url": "https://ct.mob0.com/Logo/Chrome-One.png" },
    { "fontId": "832337804", "displayname": "Club", "url": "https://ct.mob0.com/Logo/Club.png" },
    { "fontId": "830446526", "displayname": "Sushi", "url": "https://ct.mob0.com/Logo/Sushi.png" },
    { "fontId": "9", "displayname": "Comic", "url": "https://ct.mob0.com/Logo/Comic.png" },
    { "fontId": "46", "displayname": "Gold Outline", "url": "https://ct.mob0.com/Logo/Gold-Outline.png" },
    { "fontId": "18", "displayname": "Neon", "url": "https://ct.mob0.com/Logo/Neon.png" },
    { "fontId": "758282876", "displayname": "Tough", "url": "https://ct.mob0.com/Logo/Tough.png" },
    { "fontId": "1169711118", "displayname": "Flaming", "url": "https://ct.mob0.com/Logo/Flaming.gif" },
    { "fontId": "1", "displayname": "Alien Glow", "url": "https://ct.mob0.com/Logo/Alien-Glow.png" },
    { "fontId": "622058564", "displayname": "Cupid", "url": "https://ct.mob0.com/Logo/Cupid.png" },
    { "fontId": "622063540", "displayname": "Chick Flick", "url": "https://ct.mob0.com/Logo/Chick-Flick.png" },
    { "fontId": "732431452", "displayname": "Candy", "url": "https://ct.mob0.com/Logo/Candy.png" },
    { "fontId": "789574607", "displayname": "Groovy", "url": "https://ct.mob0.com/Logo/Groovy.png" },
    { "fontId": "819721038", "displayname": "Love", "url": "https://ct.mob0.com/Logo/Love.gif" },
    { "fontId": "15", "displayname": "Glowing Steel", "url": "https://ct.mob0.com/Logo/Glowing-Steel.png" },
    { "fontId": "829964308", "displayname": "Princess", "url": "https://ct.mob0.com/Logo/Princess.png" },
    { "fontId": "819515844", "displayname": "Blinkie", "url": "https://ct.mob0.com/Logo/Blinkie.gif" },
    { "fontId": "2792545512", "displayname": "Stranger", "url": "https://ct.mob0.com/Logo/Stranger.png" },
    { "fontId": "31", "displayname": "Embossed", "url": "https://ct.mob0.com/Logo/Embossed.png" },
    { "fontId": "615608693", "displayname": "Muddy", "url": "https://ct.mob0.com/Logo/Muddy.png" },
    { "fontId": "4112952183", "displayname": "Plain", "url": "https://ct.mob0.com/Logo/Plain.png" },
    { "fontId": "4112270507", "displayname": "Trogdor", "url": "https://ct.mob0.com/Logo/Trogdor.png" },
    { "fontId": "2854656927", "displayname": "Miami", "url": "https://ct.mob0.com/Logo/Miami.png" },
    { "fontId": "27", "displayname": "Old Stone", "url": "https://ct.mob0.com/Logo/Old-Stone.png" },
    { "fontId": "732414977", "displayname": "Vampire", "url": "https://ct.mob0.com/Logo/Vampire.png" },
    { "fontId": "757794054", "displayname": "Gold Bar", "url": "https://ct.mob0.com/Logo/Gold-Bar.png" },
    { "fontId": "36", "displayname": "Frosty", "url": "https://ct.mob0.com/Logo/Frosty.png" },
    { "fontId": "38", "displayname": "Wizards", "url": "https://ct.mob0.com/Logo/Wizards.png" },
    { "fontId": "29", "displayname": "3D Outline Gradient", "url": "https://ct.mob0.com/Logo/3D-Outline-Gradient.png" },
    { "fontId": "758277984", "displayname": "Saint-Patrick", "url": "https://ct.mob0.com/Logo/Saint-Patrick.png" },
    { "fontId": "4", "displayname": "Burning", "url": "https://ct.mob0.com/Logo/Burning.gif" },
    { "fontId": "758279718", "displayname": "Keen", "url": "https://ct.mob0.com/Logo/Keen.png" },
    { "fontId": "780833150", "displayname": "Skate", "url": "https://ct.mob0.com/Logo/Skate.png" },
    { "fontId": "1009848424", "displayname": "Fun", "url": "https://ct.mob0.com/Logo/Fun.png" },
    { "fontId": "732438332", "displayname": "White", "url": "https://ct.mob0.com/Logo/White.png" },
    { "fontId": "2975689126", "displayname": "Tribal", "url": "https://ct.mob0.com/Logo/Tribal.png" },
    { "fontId": "2650967346", "displayname": "Supernova", "url": "https://ct.mob0.com/Logo/Supernova.png" },
    { "fontId": "13", "displayname": "Fire", "url": "https://ct.mob0.com/Logo/Fire.png" },
    { "fontId": "37", "displayname": "iText", "url": "https://ct.mob0.com/Logo/iText.png" },
    { "fontId": "791030843", "displayname": "Easy", "url": "https://ct.mob0.com/Logo/Easy.png" },
    { "fontId": "732443655", "displayname": "Gold-Trim", "url": "https://ct.mob0.com/Logo/Gold-Trim.png" },
    { "fontId": "732429307", "displayname": "Legal", "url": "https://ct.mob0.com/Logo/Legal.png" },
    { "fontId": "21", "displayname": "Simple", "url": "https://ct.mob0.com/Logo/Simple.png" },
    { "fontId": "1779834160", "displayname": "Ice-Cube", "url": "https://ct.mob0.com/Logo/Ice-Cube.png" },
    { "fontId": "4113131447", "displayname": "Tesla", "url": "https://ct.mob0.com/Logo/Tesla.png" },
    { "fontId": "7", "displayname": "Chrome-One", "url": "https://ct.mob0.com/Logo/Chrome-One.png" },
    { "fontId": "832337804", "displayname": "Club", "url": "https://ct.mob0.com/Logo/Club.png" },
    { "fontId": "830446526", "displayname": "Sushi", "url": "https://ct.mob0.com/Logo/Sushi.png" },
    { "fontId": "9", "displayname": "Comic", "url": "https://ct.mob0.com/Logo/Comic.png" },
    { "fontId": "46", "displayname": "Gold-Outline", "url": "https://ct.mob0.com/Logo/Gold-Outline.png" },
    { "fontId": "18", "displayname": "Neon", "url": "https://ct.mob0.com/Logo/Neon.png" },
    { "fontId": "758282876", "displayname": "Tough", "url": "https://ct.mob0.com/Logo/Tough.png" },
    { "fontId": "1169711118", "displayname": "Flaming", "url": "https://ct.mob0.com/Logo/Flaming.gif" },
    { "fontId": "1", "displayname": "Alien-Glow", "url": "https://ct.mob0.com/Logo/Alien-Glow.png" },
    { "fontId": "622058564", "displayname": "Cupid", "url": "https://ct.mob0.com/Logo/Cupid.png" },
    { "fontId": "622063540", "displayname": "Chick-Flick", "url": "https://ct.mob0.com/Logo/Chick-Flick.png" },
    { "fontId": "732431452", "displayname": "Candy", "url": "https://ct.mob0.com/Logo/Candy.png" },
    { "fontId": "789574607", "displayname": "Groovy", "url": "https://ct.mob0.com/Logo/Groovy.png" },
    { "fontId": "829964308", "displayname": "Princess", "url": "https://ct.mob0.com/Logo/Princess.png" },
    { "fontId": "2792545512", "displayname": "Stranger", "url": "https://ct.mob0.com/Logo/Stranger.png" },
    { "fontId": "31", "displayname": "Embossed", "url": "https://ct.mob0.com/Logo/Embossed.png" },
    { "fontId": "615608693", "displayname": "Muddy", "url": "https://ct.mob0.com/Logo/Muddy.png" },
    { "fontId": "4112952183", "displayname": "Plain", "url": "https://ct.mob0.com/Logo/Plain.png" },
    { "fontId": "4112270507", "displayname": "Trogdor", "url": "https://ct.mob0.com/Logo/Trogdor.png" },
    { "fontId": "2854656927", "displayname": "Miami", "url": "https://ct.mob0.com/Logo/Miami.png" },
    { "fontId": "732414977", "displayname": "Vampire", "url": "https://ct.mob0.com/Logo/Vampire.png" },
    { "fontId": "757794054", "displayname": "Gold-Bar", "url": "https://ct.mob0.com/Logo/Gold-Bar.png" },
    { "fontId": "36", "displayname": "Frosty", "url": "https://ct.mob0.com/Logo/Frosty.png" },
    { "fontId": "38", "displayname": "Wizards", "url": "https://ct.mob0.com/Logo/Wizards.png" },
    { "fontId": "29", "displayname": "3D-Outline-Gradient", "url": "https://ct.mob0.com/Logo/3D-Outline-Gradient.png" },
    { "fontId": "2655376160", "displayname": "Spaced-Out", "url": "https://ct.mob0.com/Logo/Spaced-Out.png" },
    { "fontId": "4516516448", "displayname": "SAINT", "url": "https://ct.mob0.com/Logo/SAINT.png" },
    { "fontId": "8", "displayname": "Chrome-Two", "url": "https://ct.mob0.com/Logo/Chrome-Two.png" },
    { "fontId": "783758829", "displayname": "House-Arryn", "url": "https://ct.mob0.com/Logo/House-Arryn.png" },
    { "fontId": "33", "displayname": "Chromium", "url": "https://ct.mob0.com/Logo/Chromium.png" },
    { "fontId": "4110551533", "displayname": "Scavenge", "url": "https://ct.mob0.com/Logo/Scavenge.png" },
    { "fontId": "732450628", "displayname": "Bad-Acid", "url": "https://ct.mob0.com/Logo/Bad-Acid.png" },
    { "fontId": "24", "displayname": "Felt", "url": "https://ct.mob0.com/Logo/Felt.png" },
    { "fontId": "16", "displayname": "Gradient-Bevel", "url": "https://ct.mob0.com/Logo/Gradient-Bevel.png" },
    { "fontId": "615602790", "displayname": "Imprint", "url": "https://ct.mob0.com/Logo/Imprint.png" },
    { "fontId": "1783669883", "displayname": "Sugar", "url": "https://ct.mob0.com/Logo/Sugar.png" },
    { "fontId": "2222568262", "displayname": "Merry-Christmas", "url": "https://ct.mob0.com/Logo/Merry-Christmas.png" },
    { "fontId": "2654162149", "displayname": "Caster", "url": "https://ct.mob0.com/Logo/Caster.png" },
    { "fontId": "615569527", "displayname": "Snowman", "url": "https://ct.mob0.com/Logo/Snowman.png" },
    { "fontId": "612444173", "displayname": "Tie-Dyed", "url": "https://ct.mob0.com/Logo/Tie-Dyed.png" },
    { "fontId": "783756759", "displayname": "Iceberg", "url": "https://ct.mob0.com/Logo/Iceberg.png" },
    { "fontId": "4113153856", "displayname": "Apollo-11", "url": "https://ct.mob0.com/Logo/Apollo-11.png" },
    { "fontId": "1783676518", "displayname": "Candy-Stripe", "url": "https://ct.mob0.com/Logo/Candy-Stripe.png" },
    { "fontId": "759902224", "displayname": "Spring", "url": "https://ct.mob0.com/Logo/Spring.png" },
    { "fontId": "4112421173", "displayname": "Greek-Gold", "url": "https://ct.mob0.com/Logo/Greek-Gold.png" },
    { "fontId": "1408867449", "displayname": "Dragon", "url": "https://ct.mob0.com/Logo/Dragon.png" },
    { "fontId": "39", "displayname": "Particle", "url": "https://ct.mob0.com/Logo/Particle.png" },
    { "fontId": "830469381", "displayname": "Water", "url": "https://ct.mob0.com/Logo/Water.png" },
    { "fontId": "25", "displayname": "Outline", "url": "https://ct.mob0.com/Logo/Outline.png" },
    { "fontId": "852774362", "displayname": "Lava", "url": "https://ct.mob0.com/Logo/Lava.png" },
    { "fontId": "4112260450", "displayname": "Romance", "url": "https://ct.mob0.com/Logo/Romance.png" },
    { "fontId": "2172004512", "displayname": "Sword", "url": "https://ct.mob0.com/Logo/Sword.png" },
    { "fontId": "43", "displayname": "Molten-Core", "url": "https://ct.mob0.com/Logo/Molten-Core.gif" },
    { "fontId": "35", "displayname": "Grunge", "url": "https://ct.mob0.com/Logo/Grunge.png" },
    { "fontId": "42", "displayname": "Plastic", "url": "https://ct.mob0.com/Logo/Plastic.png" },
    { "fontId": "17", "displayname": "Slab", "url": "https://ct.mob0.com/Logo/Slab.png" },
    { "fontId": "4112242098", "displayname": "Will-You-Marry-Me", "url": "https://ct.mob0.com/Logo/Will-You-Marry-Me.png" },
    { "fontId": "732453157", "displayname": "Studio-54", "url": "https://ct.mob0.com/Logo/Studio-54.png" },
    { "fontId": "742083872", "displayname": "Serial", "url": "https://ct.mob0.com/Logo/Serial.png" },
    { "fontId": "2222569522", "displayname": "Happy-New-Year", "url": "https://ct.mob0.com/Logo/Happy-New-Year.png" },
    { "fontId": "830474754", "displayname": "Dark", "url": "https://ct.mob0.com/Logo/Dark.png" },
    { "fontId": "852819205", "displayname": "Gunmetal", "url": "https://ct.mob0.com/Logo/Gunmetal.png" },
    { "fontId": "4516496663", "displayname": "Black-Gold", "url": "https://ct.mob0.com/Logo/Black-Gold.png" },
    { "fontId": "1279361064", "displayname": "Liquid-Gold", "url": "https://ct.mob0.com/Logo/Liquid-Gold.png" },
    { "fontId": "611409107", "displayname": "Lasers", "url": "https://ct.mob0.com/Logo/Lasers.png" },
    { "fontId": "783763343", "displayname": "Cheetah", "url": "https://ct.mob0.com/Logo/Cheetah.png" },
    { "fontId": "2655372531", "displayname": "Robot", "url": "https://ct.mob0.com/Logo/Robot.png" },
    { "fontId": "749791093", "displayname": "Rage", "url": "https://ct.mob0.com/Logo/Rage.png" },
    { "fontId": "12", "displayname": "Cutout", "url": "https://ct.mob0.com/Logo/Cutout.png" },
    { "fontId": "599808502", "displayname": "Klingon", "url": "https://ct.mob0.com/Logo/Klingon.png" }
];

// Define the structure of a CoolText object for clarity
